# Generated by Django 4.1.2 on 2022-10-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Blog',
        ),
    ]
